import { Store } from "./types";

export const stores: Store[] = [
  {
    id: 1,
    name: "TYLER'S",
    location: "Main Street, Downtown",
    totalItems: 1250,
    lowStockItems: 8,
    outOfStock: 2,
    inventoryHealth: 85,
  },
  {
    id: 2,
    name: "Racquet & Jog",
    location: "Shopping Center, North",
    totalItems: 980,
    lowStockItems: 12,
    outOfStock: 1,
    inventoryHealth: 78,
  },
  {
    id: 3,
    name: "Whole Earth Provision Co.",
    location: "Airport Terminal",
    totalItems: 650,
    lowStockItems: 5,
    outOfStock: 0,
    inventoryHealth: 92,
  },
  {
    id: 4,
    name: "Sun & Ski Sports",
    location: "Industrial District",
    totalItems: 3200,
    lowStockItems: 25,
    outOfStock: 8,
    inventoryHealth: 72,
  },
  {
    id: 5,
    name: "Cavender's",
    location: "West Side Plaza",
    totalItems: 1450,
    lowStockItems: 15,
    outOfStock: 3,
    inventoryHealth: 80,
  },
  {
    id: 6,
    name: "Lone Star Dry Goods",
    location: "Historic District",
    totalItems: 890,
    lowStockItems: 6,
    outOfStock: 1,
    inventoryHealth: 88,
  },
  {
    id: 7,
    name: "Atwoods Ranch & Home",
    location: "Rural Highway",
    totalItems: 2100,
    lowStockItems: 18,
    outOfStock: 4,
    inventoryHealth: 75,
  },
  {
    id: 8,
    name: "SCHEELS (The Colony)",
    location: "The Colony Mall",
    totalItems: 1800,
    lowStockItems: 10,
    outOfStock: 2,
    inventoryHealth: 86,
  },
  {
    id: 9,
    name: "Buckle",
    location: "Fashion Center",
    totalItems: 750,
    lowStockItems: 8,
    outOfStock: 0,
    inventoryHealth: 90,
  },
  {
    id: 10,
    name: "Wild West Boot Store",
    location: "Cowboy District",
    totalItems: 1100,
    lowStockItems: 12,
    outOfStock: 2,
    inventoryHealth: 82,
  },
] 